data:
  image_dir: "hmu_gc_data/all_image"
  csv_path: "data/labels.csv"
  output_dir: "outputs_optimized"
  checkpoint_dir: "outputs_optimized/checkpoints"
  log_dir: "outputs_optimized/logs"
  scores_file: "outputs_optimized/scores.csv"
dataset:
  num_classes: 8
  class_names: ["ADI", "DEB", "LYM", "MUC", "MUS", "NOR", "STR", "TUM"]
  input_channels: 3
  n_folds: 10
  stratify: true
  seed: 42
  target_col: "label"
  input_col: "filename"

augmentations:
  strategy: "per_class"
  input_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

  classes:
    ADI:
      transforms:
        - RandomBrightnessContrast:
            brightness_limit: 0.1
            contrast_limit: 0.1
            p: 1.0
        - HueSaturationValue:
            val_shift_limit: 5
            p: 0.5
        - CLAHE:
            clip_limit: 3.0
            tile_grid_size: [8, 8]
            p: 0.5

    DEB:
      transforms:
        - ShiftScaleRotate:
            shift_limit: 0.1
            scale_limit: 0.1
            rotate_limit: 30
            p: 0.8
        - RandomBrightnessContrast:
            brightness_limit: 0.15
            contrast_limit: 0.2
            p: 0.7
        - CoarseDropout:
            max_holes: 3
            max_height: 20
            max_width: 20
            fill_value: 0
            p: 0.3

    LYM:
      transforms:
        - Rotate:
            limit: 10
            p: 0.5
        - HorizontalFlip:
            p: 0.5

    MUC:
      transforms:
        - RandomBrightnessContrast:
            brightness_limit: 0.05
            contrast_limit: 0.15
            p: 0.8

    MUS:
      transforms:
        - Rotate:
            limit: 5
            p: 0.7
        - CLAHE:
            p: 0.4
        - Sharpen:
            alpha: [0.1, 0.2]
            lightness: [0.7, 0.9]
            p: 0.3

    NOR:
      transforms:
        - RandomBrightnessContrast:
            brightness_limit: 0.1
            contrast_limit: 0.2
            p: 0.8
        - HueSaturationValue:
            hue_shift_limit: 5
            sat_shift_limit: 10
            val_shift_limit: 5
            p: 0.5

    STR:
      transforms:
        - Rotate:
            limit: 10
            p: 0.7
        - ElasticTransform:
            alpha: 0.5
            sigma: 10
            alpha_affine: 10
            p: 0.3

    TUM:
      transforms:
        - RandomBrightnessContrast:
            brightness_limit: 0.2
            contrast_limit: 0.1
            p: 0.8
        - Affine:
            scale: [0.95, 1.05]
            rotate: [-10, 10]
            translate_percent: 0.05
            p: 0.5
        - Sharpen:
            alpha: [0.2, 0.4]
            lightness: [0.9, 1.0]
            p: 0.4
models:
  - name: "efficientnet_b0"
    input_size: 224
    dropout: 0.20
    weight: 0.25
    learning_rate: 0.0001
    weight_decay: 0.0001
  - name: "efficientnet_b3"
    input_size: 300
    dropout: 0.35
    weight: 0.40
    learning_rate: 0.00005
    weight_decay: 0.0002
  - name: "efficientnet_b4"
    input_size: 380
    dropout: 0.45
    weight: 0.40
    weight_decay: 0.0003
    learning_rate: 0.00003
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "cosine_annealing"
  use_amp: true   # Automatic Mixed Precision
  early_stopping:
    patience: 10
    monitor: "val_macro_f1"
    mode: "max"
  loss_function: "cross_entropy"
  label_smoothing: 0.0  # Pode ser ajustado para 0.1 em estudos futuros
  metric: "macro_f1"
  logging:
    format: "csv"
    tensorboard: true
    wandb: false
  balance_sampler: false  # conforme Wolpert e CHD: diversidade sem enviesamento artificial
  distributed_training: false
ensemble:
  type: "stacking"  # options: stacking, soft_voting
  use_validation_set: true
  meta_model: "logistic_regression"
  stacking_use_probs: true
evaluation:
  metrics: ["accuracy", "balanced_accuracy", "f1_macro", "kappa"]
  generate_confusion_matrix: true
  generate_roc_curves: true
  save_predictions: true
  visualize_class_distribution: true
stats:
  tests: ["friedman", "nemenyi"]
  alpha: 0.05
  generate_rank_plot: true
