data:
  image_dir: "hmu_gc_data/test_sandbox_images"
  csv_path: "data/sandbox_labels.csv"
  output_dir: "outputs_sandbox"
  checkpoint_dir: "outputs_sandbox/checkpoints"
  log_dir: "outputs_sandbox/logs"
  scores_file: "outputs_sandbox/scores.csv"

dataset:
  num_classes: 8
  class_names: ["ADI", "DEB", "LYM", "MUC", "MUS", "NOR", "STR", "TUM"]
  input_channels: 3
  n_folds: 2
  stratify: true
  seed: 42
  target_col: "label"
  input_col: "filename"

augmentations:
  strategy: "per_class"
  input_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  classes: {}  # pode estar vazio para evitar transformações pesadas

models:
  - name: "efficientnet_b0"
    input_size: 224
    dropout: 0.25
    weight: 1.0
  - name: "efficientnet_b3"
    input_size: 300
    dropout: 0.30
    weight: 0.35
  - name: "efficientnet_b4"
    input_size: 380
    dropout: 0.40
    weight: 0.40

training:
  epochs: 2
  batch_size: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "cosine_annealing"
  use_amp: false
  early_stopping:
    patience: 2
    monitor: "val_macro_f1"
    mode: "max"
  loss_function: "cross_entropy"
  metric: "macro_f1"
  logging:
    format: "csv"
    tensorboard: false
    wandb: false
  balance_sampler: false
  distributed_training: false

ensemble:
  type: "soft_voting"
  use_validation_set: false

evaluation:
  metrics: ["accuracy", "f1_macro"]
  generate_confusion_matrix: true
  generate_roc_curves: true
  save_predictions: true
  visualize_class_distribution: false

stats:
  tests: ["friedman"]
  alpha: 0.05
  generate_rank_plot: false
